sonar.projectKey=calculadora-app
sonar.projectName=Calculadora React Native
sonar.projectVersion=1.0
sonar.sources=src,App.tsx
sonar.exclusions=**/node_modules/**,**/.expo/**,**/*.test.ts,**/*.test.tsx
sonar.sourceEncoding=UTF-8